#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  shift
  export RDECK_BASE="$shome/vendor"
  exec rundeck "$@"
}

main "$@"

